[project]
name = "dqn"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "flappy-bird-gymnasium>=0.4.0",
    "gymnasium>=1.2.2",
]
